version: '3.0'

services:
  postgres:
    build: .
    container_name: test-postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
